name: Compile

on:
  push:
    branches: [ "*" ]

jobs:
  Compile:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest

    runs-on: ${{matrix.os}}

    steps:
      - uses: actions/checkout@v5.0.0
        with:
          submodules: recursive

      - name: Configure CMake (Windows)
        if: runner.os == 'Windows'
        run: cmake . -G="MinGW Makefiles"

      - name: Configure CMake (*nix)
        if: runner.os != 'Windows'
        run: cmake .

      - name: Compile
        run: cmake --build .